# Generated by Django 3.0.5 on 2020-09-02 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='_from',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='experience',
            name='_to',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
