# Generated by Django 3.0.5 on 2020-08-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
